version: '3.8'

services:
  web:
    # env_file: deck_api_perm_project/.env 
    build: .
    command: gunicorn wb_api_perm_project.wsgi:application --bind  0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
