version: '3'

services:
  web:
    # env_file: wb_api_project/.env 
    build: .
    command: gunicorn wb_api_project.wsgi:application --bind  0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
