# Generated by Django 3.2.2 on 2021-05-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_app', '0002_categorynotes_classlist_scoretable_student_whiteboard_whiteboardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scheduled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
