# Generated by Django 3.2.2 on 2021-05-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb_app', '0002_categorynotes_classlist_scoretable_student_whiteboard_whiteboardimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_hist',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='whiteboard',
            name='student_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wb_app.student'),
        ),
    ]
